[[plugins]]
  package = "netlify-plugin-js-obfuscator"
  [plugins.inputs]
        compact = true
        simplify = true
        numbersToExpressions = true
        shuffleStringArray = true
        splitStrings = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://vatsim1.netlify.app"
