[[plugins]]
  package = "netlify-plugin-js-obfuscator"
    [plugins.inputs]
      obfuscationOptions = '''
        {
          "compact": true,
          "controlFlowFlattening": true,
          "deadCodeInjection": true,
          "deadCodeInjectionThreshold": 0.4,
          "identifierNamesGenerator": "hexadecimal",
          "rotateStringArray": true,
          "selfDefending": true,
          "shuffleStringArray": true,
          "splitStrings": true,
          "splitStringsChunkLength": 5,
          "stringArray": true,
          "stringArrayEncoding": ["rc4"],
          "stringArrayWrappersCount": 2,
          "stringArrayWrappersChainedCalls": true,
          "stringArrayWrappersParametersMaxCount": 5,
          "stringArrayWrappersType": "function",
          "transformObjectKeys": true,
          "unicodeEscapeSequence": false
        }
      '''
[[plugins]]
  package = "netlify-plugin-minify-js"

[[plugins]]
  package = "netlify-plugin-minify-css"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "https://vatsim1.netlify.app"
