[[plugins]]
  package = "netlify-plugin-js-obfuscator"
  [plugins.inputs]
        compact = true
        simplify = true
        numbersToExpressions = true
        shuffleStringArray = true
        splitStrings = true

[build]
  command = "npm run build"
  publish = "public"


[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://vatsim1.netlify.app"
